apiVersion: v1
kind: Namespace
metadata:
  name: jide

---

apiVersion: v1
kind: Service
metadata:
  name: jide-app
  namespace: jide
  labels:
    app: jide-app
spec:
  ports:
    - port: 3000
  selector:
    app: jide-app
  type: LoadBalancer # Required by docker-for-mac kubernetes to expose locally

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jide-app
  namespace: jide
  labels:
    app: jide-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jide-app
  template:
    metadata:
      labels:
        app: jide-app
    spec:
      containers:
        - name: jide
          image: cflynnus/jide
          ports:
            - containerPort: 3000
